name: Deploy MERN Stack

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install backend dependencies
      run: npm install

    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm install
        npm run build

    - name: Install PM2
      run: npm install pm2 -g

    - name: Add EC2 Host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        EC2_USER: ubuntu
        EC2_HOST: ${{ secrets.EC2_HOST }}
        PM2_NAME: cherryshades-pm2
        NODE_ENV: ${{ secrets.NODE_ENV }}
        PORT: ${{ secrets.PORT }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
      run: |
        echo "$SSH_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -i deploy_key.pem $EC2_USER@$EC2_HOST "sudo mkdir -p /home/ubuntu/cherryshades-test && sudo chown -R $EC2_USER:$EC2_USER /home/ubuntu/cherryshades-test"
        rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.github' -e "ssh -i deploy_key.pem" . $EC2_USER@$EC2_HOST:/home/ubuntu/cherryshades-test/
        ssh -i deploy_key.pem $EC2_USER@$EC2_HOST << EOF
          cd /home/ubuntu/cherryshades-test
          echo "NODE_ENV=${NODE_ENV}" >> .env
          echo "PORT=${PORT}" >> .env
          echo "MONGO_URI=${MONGO_URI}" >> .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          echo "PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}" >> .env
          npm install
          cd frontend
          npm install
          npm run build
          cd ..
          pm2 restart ${PM2_NAME} || pm2 start /home/ubuntu/cherryshades-test/backend/server.js --name ${PM2_NAME}
          sudo chown -R ubuntu:ubuntu /home/ubuntu/cherryshades-test
          sudo chmod -R 755 /home/ubuntu/cherryshades-test
          exit
        EOF
      shell: bash
