name: Deploy Process of Cherryshades-test

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Application
      run: |
        ssh -i deploy_key.pem $EC2_USER@$EC2_HOST <<-EOF
          cd /home/ubuntu/cherryshades-test
          echo "NODE_ENV=${NODE_ENV}" > .env
          echo "PORT=${PORT}" >> .env
          echo "MONGO_URI=${MONGO_URI}" >> .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          echo "PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}" >> .env
          npm install
          cd frontend
          npm install
          npm run build
          cd ..
          pm2 stop ${PM2_NAME} || true
          pm2 delete ${PM2_NAME} || true
          pm2 start /home/ubuntu/cherryshades-test/backend/server.js --name ${PM2_NAME}
        EOF
      shell: bash

    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      EC2_USER: ${{ secrets.EC2_USER}}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      PM2_NAME: ${{ secrets.PM2_NAME }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}