name: Deploy Process of Cherryshades-test

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: npm ci --prefix cherryshades/backend

      - name: Install frontend dependencies and build
        run: |
          npm ci --prefix cherryshades/frontend
          npm run build --prefix cherryshades/frontend

      - name: Prepare SSH Key and Add to SSH Agent
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          eval $(ssh-agent -s)
          ssh-add deploy_key.pem
        shell: bash

      - name: Add EC2 Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          rsync -avz --exclude-from='.scpignore' -e "ssh -i deploy_key.pem" cherryshades/ $EC2_USER@$EC2_HOST:/home/ubuntu/cherryshades/
          ssh -i deploy_key.pem $EC2_USER@$EC2_HOST <<-EOF
            cd /home/ubuntu/cherryshades
            echo "NODE_ENV=${NODE_ENV}" > .env
            echo "PORT=${PORT}" >> .env
            echo "MONGO_URI=${MONGO_URI}" >> .env
            echo "JWT_SECRET=${JWT_SECRET}" >> .env
            echo "PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}" >> .env
            npm ci --prefix backend
            pm2 stop ${PM2_NAME} || true
            pm2 delete ${PM2_NAME} || true
            pm2 start /home/ubuntu/cherryshades/backend/server.js --name ${PM2_NAME}
          EOF
        shell: bash

    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      PM2_NAME: ${{ secrets.PM2_NAME }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
