name: Deploy Process of Cherryshades-test

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare SSH Key
      run: |
        echo "$SSH_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem

    - name: Add SSH Key to SSH Agent
      run: |
        eval $(ssh-agent -s)
        ssh-add deploy_key.pem
      shell: bash

    - name: Verify SSH Key
      run: ssh-keygen -lf deploy_key.pem

    - name: Add EC2 Host to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh -i deploy_key.pem $EC2_USER@$EC2_HOST "echo 'SSH connection successful!'"
      shell: bash

    - name: Remove Existing Directory on EC2
      run: |
        ssh -i deploy_key.pem $EC2_USER@$EC2_HOST "rm -rf /home/ubuntu/cherryshades-test"
      shell: bash

    - name: Clone Repository on EC2
      run: |
        ssh -i deploy_key.pem $EC2_USER@$EC2_HOST "git clone https://github.com/Manjunath-Gowdar/cherryshades-test.git /home/ubuntu/cherryshades-test"
      shell: bash

    - name: Copy Files to EC2
      run: |
        rsync -avz --exclude-from='.scpignore' -e "ssh -i deploy_key.pem" cherryshades-test/ $EC2_USER@$EC2_HOST:/home/ubuntu/cherryshades-test/
      shell: bash

    - name: Adjust permissions on EC2
      run: |
        ssh -i deploy_key.pem $EC2_USER@$EC2_HOST "sudo chown -R $EC2_USER:$EC2_USER /home/ubuntu/cherryshades-test/frontend/build && sudo chmod -R 755 /home/ubuntu/cherryshades-test/frontend/build"
      shell: bash

    - name: Deploy Application on EC2
      run: |
        ssh -i deploy_key.pem $EC2_USER@$EC2_HOST <<-EOF
          cd /home/ubuntu/cherryshades-test
          echo "NODE_ENV=${NODE_ENV}" > .env
          echo "PORT=${PORT}" >> .env
          echo "MONGO_URI=${MONGO_URI}" >> .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          echo "PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}" >> .env
          
          # Install backend dependencies
          cd backend
          npm install
          
          # Install frontend dependencies and build
          cd ../frontend
          npm install
          npm run build
          
          # Manage application process with PM2
          cd ..
          pm2 stop ${PM2_NAME} || true
          pm2 delete ${PM2_NAME} || true
          pm2 start /home/ubuntu/cherryshades-test/backend/server.js --name ${PM2_NAME}
        EOF
      shell: bash

    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      EC2_USER: ${{ secrets.EC2_USER}}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      PM2_NAME: ${{ secrets.PM2_NAME }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
